spring:
  profiles:
    active:local
---
spring:
  profiles:local
  kafka:
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializzer
      value-serializer: org.apache.kafka.common.serialization.StringSerializzer
      properties:
        acks: all
        retries: 10
    admin:
      properties:
        bootstrap.servers: localhost:9092,localhost:9093,localhost:9094
---
spring:
  profiles:dev
  kafka:
    template:
      default-topic: library-event
    producer:
      bootstrap-servers: dev:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializzer
      value-serializer:org.apache.kafka.common.serialization.StringSerializzer
---
spring:
  profiles:prod
  kafka:
    producer:
      bootstrap-servers: prod:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializzer
      value-serializer:org.apache.kafka.common.serialization.StringSerializzer
